DROP TABLE IF EXISTS feedback CASCADE;
DROP TABLE IF EXISTS request CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS complaint CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
